-- =============================================================================
-- CARGA DE DEMONSTRACAO — T_PB_RESPONSAVEL e T_PB_ANIMAL
-- =============================================================================
-- Popula as duas tabelas do CRUD com conteudo de negocio antes da demonstracao,
-- para que a consulta ja tenha o que mostrar e a atualizacao e a exclusao
-- incidam sobre dados reais.
--
-- Executar UMA vez, depois do 05_aci-java.sh, conectado como PETBUDDIES_CUIDADO:
--
--   sqlplus PETBUDDIES_CUIDADO/<senha>@<fqdn>:1521/XEPDB1 @carga_demonstracao.sql
--
-- NENHUM ID E ESCRITO A MAO. As chaves sao GENERATED BY DEFAULT ON NULL AS
-- IDENTITY: gravar um id explicito nao avanca o gerador, e o proximo animal
-- criado pela aplicacao colidiria com esta carga. Por isso o vinculo do animal
-- com o dono e resolvido por subconsulta no e-mail, que e unico por pessoa.
-- =============================================================================

-- --- tutores ----------------------------------------------------------------

INSERT INTO T_PB_RESPONSAVEL (NM_NOME_RESPONSAVEL, TL_TELEFONE, EM_EMAIL)
VALUES ('Joana Ribeiro', '11962547781', 'joana.ribeiro@email.com');

INSERT INTO T_PB_RESPONSAVEL (NM_NOME_RESPONSAVEL, TL_TELEFONE, EM_EMAIL)
VALUES ('Carlos Tanaka', '11974663092', 'carlos.tanaka@email.com');

-- --- animais ----------------------------------------------------------------
-- Tres animais entre os dois tutores: o lado "N" do relacionamento aparece de
-- fato, com um tutor levando mais de um animal.

INSERT INTO T_PB_ANIMAL (NM_NOME_ANIMAL, ES_ESPECIE, RC_RACA, PT_PORTE, SX_SEXO,
                         DT_DATA_NASCIMENTO, NR_PESO, CN_CONDICAO_CRONICA,
                         CT_CASTRADO, OB_ALERGIA, OB_OBSERVACOES, ID_RESPONSAVEL)
VALUES ('Amora', 'CACHORRO', 'Border Collie', 'MEDIO', 'FEMEA',
        DATE '2021-04-18', 17.30, 0, 1,
        'Reacao a sulfas',
        'Displasia coxofemoral leve acompanhada desde 2024',
        (SELECT ID_RESPONSAVEL FROM T_PB_RESPONSAVEL
          WHERE EM_EMAIL = 'joana.ribeiro@email.com'));

INSERT INTO T_PB_ANIMAL (NM_NOME_ANIMAL, ES_ESPECIE, RC_RACA, PT_PORTE, SX_SEXO,
                         DT_DATA_NASCIMENTO, NR_PESO, CN_CONDICAO_CRONICA,
                         CT_CASTRADO, OB_OBSERVACOES, ID_RESPONSAVEL)
VALUES ('Tofu', 'GATO', 'Siames', 'PEQUENO', 'MACHO',
        DATE '2023-09-02', 4.10, 0, 1,
        'Cistite idiopatica recorrente, com dieta umida prescrita',
        (SELECT ID_RESPONSAVEL FROM T_PB_RESPONSAVEL
          WHERE EM_EMAIL = 'joana.ribeiro@email.com'));

INSERT INTO T_PB_ANIMAL (NM_NOME_ANIMAL, ES_ESPECIE, RC_RACA, PT_PORTE, SX_SEXO,
                         DT_DATA_NASCIMENTO, NR_PESO, CN_CONDICAO_CRONICA,
                         CT_CASTRADO, OB_OBSERVACOES, ID_RESPONSAVEL)
VALUES ('Nuvem', 'CACHORRO', 'Golden Retriever', 'GRANDE', 'FEMEA',
        DATE '2019-11-25', 31.80, 1, 0,
        'Hipotireoidismo em tratamento continuo',
        (SELECT ID_RESPONSAVEL FROM T_PB_RESPONSAVEL
          WHERE EM_EMAIL = 'carlos.tanaka@email.com'));

COMMIT;

-- --- conferencia ------------------------------------------------------------

SELECT r.NM_NOME_RESPONSAVEL AS TUTOR,
       a.NM_NOME_ANIMAL      AS ANIMAL,
       a.ES_ESPECIE          AS ESPECIE,
       a.NR_PESO             AS PESO
  FROM T_PB_RESPONSAVEL r
  LEFT JOIN T_PB_ANIMAL a ON a.ID_RESPONSAVEL = r.ID_RESPONSAVEL
 ORDER BY r.ID_RESPONSAVEL, a.ID_ANIMAL;
