-- =============================================================================
-- V1 — BASELINE DO CUIDADO (serviço Java)
-- =============================================================================
-- As DEZOITO tabelas de que este serviço é dono, com chave primária, restrições
-- de domínio, as FKs INTERNAS ao cuidado e os índices.
--
-- AMPLIADO NO PR-J13 (ADR s3-25) — níveis 3 a 5 do registro: janela de
-- atendimento, registro de atendimento, procedimento, prescrição e regra de
-- prescrição. Prescrição e regra de prescrição nascem completas aqui — nunca
-- tiveram controller no .NET, só entidade e configuração de EF. As duas são
-- IMUTÁVEIS por decisão de domínio (a prescrição por ADR s3-09; a regra, por
-- carregar a mesma assinatura): sem UPDATE, sem DELETE, AT_UPDATED_AT nasce e
-- fica nulo.
--
-- REESCRITO NO PR-J8 (ADR s3-24, 09/09) e AMPLIADO NO PR-J11 (ADR s3-25),
-- e não acrescentado num V4. Legítimo por um motivo só: este baseline NUNCA
-- rodou contra o Oracle. Se tiver rodado antes do merge, este arquivo volta ao
-- que era e a mudança vira V4.
--
-- O QUE MUDOU NO PR-J11 (ADR s3-25) — O REGISTRO COMEÇA A MIGRAR PARA CÁ
--   · Este serviço passou a ser a API única do produto: ele absorve as onze
--     tabelas do registro, uma onda por nível de dependência. O nível 0 são as
--     duas raízes, T_PB_CLINICA e T_PB_RESPONSAVEL, e são as que entram aqui.
--     As outras nove chegam em J12–J16, e o baseline vai a dezesseis tabelas.
--   · O V2 DEIXOU DE EXISTIR. Ele guardava as nove FKs que cruzavam serviço, e
--     nenhuma chave cruza mais nada: cada serviço tem o banco próprio, um RM
--     por serviço, e o schema deste arquivo é exclusivo do Java. As FKs cujas
--     duas pontas já vivem aqui voltaram para o bloco de FKs internas — é o
--     caso de FK_USUARIO_RESPONSAVEL. As que ainda apontam para tabela não
--     migrada voltam junto com ela, no PR do nível dela.
--   · Some com o V2 a projeção domain/readonly, que lia o registro no schema do
--     .NET e nunca teve consumidor.
--
-- O QUE JÁ TINHA MUDADO NO PR-J8 (ADR s3-24)
--   · T_PB_CHECKIN_RESULTADO deixou de existir. As quatro colunas de decisão
--     (ID_CHECKIN, TP_DESFECHO, NR_DOSE_APLICADA, ID_REGRA_APLICADA) moram dentro
--     de T_PB_ITEM_PLANO_CUIDADO, ao lado de ID_PROCEDIMENTO e DT_EXECUTADO_EM,
--     que já estavam lá: são as duas metades do mesmo padrão de baixa.
--   · Sete tabelas renomeadas e dez colunas de enum sufixadas (s3-24 §7b).
--   · T_PB_PROTOCOLO perdeu porte, sexo, castração e faixa de idade — o matching
--     por perfil do pet era herança do bot. Sobrou ES_ESPECIE.
--   · TP_DATA_BASE (ex-TP_ANCORA) perdeu INSTANCIACAO e ganhou ULTIMA_REALIZACAO.
--   · T_PB_PLANO_CUIDADO ganhou TP_CATEGORIA_PLANO, própria e não herdada do
--     protocolo — é o que permite plano de tratamento sem protocolo.
--
-- AS ENTIDADES JPA DE T_PB_CHECKIN E T_PB_CONDICAO_OBSERVADA NASCEM NO PR-J6.
-- A tabela nasce aqui, e isso não quebra o `validate`: ele só confere o que está
-- mapeado.
--
-- TODA PK É NUMBER(19) NESTE ARQUIVO, inclusive nas tabelas do registro, onde o
-- DDL da disciplina declara NUMBER(10). A assimetria vinha do int do C# contra o
-- Long do Java e morreu com o s3-25, porque o Java passou a ser dono dos dois
-- lados. `validate` NÃO pega essa divergência — o dialeto Oracle compara família
-- de tipo, não precisão —, então ela sobreviveria em silêncio.
--
-- CORRIGIDO NO PR-J12: o J11 declarou T_PB_CLINICA e T_PB_RESPONSAVEL com
-- NUMBER(10). O DDL da disciplina não muda por isso: são bancos diferentes
-- desde o s3-25.
--
-- FONTE: database/src/01_ddl.sql, commit a73a473. Este arquivo é derivado; o DDL
-- da disciplina de banco é o canônico em tudo menos na precisão das PKs.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- T_PB_CLINICA — a clínica. Raiz do registro: nada de veterinário nem de
-- condição clínica existe antes dela (ADR s3-16).
--
-- O CNPJ é a identidade externa da clínica e não repete. A aplicação recusa
-- antes, com 409, para que a violação chegue como conflito de domínio e não
-- como erro de driver — mas a garantia é esta restrição, não o código.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CLINICA (
    ID_CLINICA        NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME_CLINICA   VARCHAR2(150)  NOT NULL,
    NR_CNPJ           VARCHAR2(14)   NOT NULL,
    TL_TELEFONE       VARCHAR2(20)   NOT NULL,
    EM_EMAIL          VARCHAR2(254),
    CA_CREATED_AT     TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT     TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CLINICA PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UK_CLINICA_CNPJ UNIQUE (NR_CNPJ)
);

-- -----------------------------------------------------------------------------
-- T_PB_RESPONSAVEL — o tutor. Sem CPF, sem nascimento e sem endereço: o cadastro
-- do app não pede (decisão I).
--
-- NENHUMA COLUNA É ÚNICA AQUI, e é de propósito. TL_TELEFONE é obrigatório mas
-- repete — dois tutores da mesma casa dividem o número —, e EM_EMAIL é nulável,
-- porque o cadastro nasce no balcão da clínica. Quem procurar unicidade neste
-- cadastro não vai achar: a identidade do tutor é a linha, não o contato.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_RESPONSAVEL (
    ID_RESPONSAVEL        NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME_RESPONSAVEL   VARCHAR2(150)  NOT NULL,
    TL_TELEFONE           VARCHAR2(20)   NOT NULL,
    EM_EMAIL              VARCHAR2(254),
    CA_CREATED_AT         TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT         TIMESTAMP(7),
    CONSTRAINT PK_T_PB_RESPONSAVEL PRIMARY KEY (ID_RESPONSAVEL)
);

-- -----------------------------------------------------------------------------
-- T_PB_VETERINARIO — quem assina.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_VETERINARIO (
    ID_VETERINARIO       NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME_VETERINARIO  VARCHAR2(150)  NOT NULL,
    NR_CRMV              VARCHAR2(30)   NOT NULL,
    EM_EMAIL             VARCHAR2(254),
    AT_ATIVO             NUMBER(1)      DEFAULT 1 NOT NULL,
    ID_CLINICA           NUMBER(19)     NOT NULL,
    CA_CREATED_AT        TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT        TIMESTAMP(7),
    CONSTRAINT PK_T_PB_VETERINARIO PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT UK_VETERINARIO_CRMV UNIQUE (NR_CRMV),
    CONSTRAINT CK_VETERINARIO_ATIVO CHECK (AT_ATIVO IN (0,1))
);

-- -----------------------------------------------------------------------------
-- T_PB_ANIMAL — o pet. Absorveu T_PB_TIPO_ANIMAL e T_PB_PRONTUARIO (decisão H).
-- O porte é do indivíduo: antes da fusão, corrigir o porte de um pet alterava o
-- de todos que compartilhavam a linha de tipo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_ANIMAL (
    ID_ANIMAL            NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME_ANIMAL       VARCHAR2(150)  NOT NULL,
    ES_ESPECIE           VARCHAR2(50)   NOT NULL,
    RC_RACA              VARCHAR2(100)  DEFAULT 'SEM_RACA' NOT NULL,
    PT_PORTE             VARCHAR2(50)   NOT NULL,
    SX_SEXO              VARCHAR2(50)   NOT NULL,
    DT_DATA_NASCIMENTO   DATE           NOT NULL,
    NR_PESO              NUMBER(5,2),
    CN_CONDICAO_CRONICA  NUMBER(1)      DEFAULT 0 NOT NULL,
    CT_CASTRADO          NUMBER(1)      DEFAULT 0 NOT NULL,
    FT_FOTO              VARCHAR2(500),
    OB_ALERGIA           VARCHAR2(2000),
    OB_OBSERVACOES       VARCHAR2(2000),
    ID_RESPONSAVEL       NUMBER(19)     NOT NULL,
    CA_CREATED_AT        TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT        TIMESTAMP(7),
    CONSTRAINT PK_T_PB_ANIMAL PRIMARY KEY (ID_ANIMAL),
    CONSTRAINT CK_ANIMAL_ESPECIE CHECK (ES_ESPECIE IN
        ('CACHORRO','GATO','PASSARO','COELHO','HAMSTER','OUTRO')),
    CONSTRAINT CK_ANIMAL_PORTE CHECK (PT_PORTE IN
        ('MINI','PEQUENO','MEDIO','GRANDE','GIGANTE')),
    CONSTRAINT CK_ANIMAL_SEXO CHECK (SX_SEXO IN ('MACHO','FEMEA')),
    CONSTRAINT CK_ANIMAL_CRONICA CHECK (CN_CONDICAO_CRONICA IN (0,1)),
    CONSTRAINT CK_ANIMAL_CASTRADO CHECK (CT_CASTRADO IN (0,1))
);

-- -----------------------------------------------------------------------------
-- T_PB_CONSULTA — agendamento e comparecimento. Vem antes da janela porque a
-- janela é que aponta para ela: a reserva é por referência, não por comparação
-- de horário.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CONSULTA (
    ID_CONSULTA          NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TP_TIPO_CONSULTA     VARCHAR2(50)   NOT NULL,
    DH_DATA_HORA         TIMESTAMP(7)   NOT NULL,
    ST_STATUS_CONSULTA   VARCHAR2(50)   NOT NULL,
    OB_OBSERVACAO        VARCHAR2(2000),
    MT_MOTIVO            VARCHAR2(2000),
    ID_ANIMAL            NUMBER(19)     NOT NULL,
    ID_VETERINARIO       NUMBER(19)     NOT NULL,
    CA_CREATED_AT        TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT        TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT CK_CONSULTA_TIPO CHECK (TP_TIPO_CONSULTA IN
        ('ROTINA','VACINACAO','EXAME','RETORNO','EMERGENCIA')),
    CONSTRAINT CK_CONSULTA_STATUS CHECK (ST_STATUS_CONSULTA IN
        ('AGENDADA','CONFIRMADA','REALIZADA','CANCELADA','NAO_COMPARECEU'))
);

-- -----------------------------------------------------------------------------
-- T_PB_CONDICAO_CLINICA — o catálogo que o check-in avalia.
--
-- Os nomes das colunas de enum são TP_DADO e TP_FONTE_VALOR desde o PR-N10.
-- Os CHECKs mantêm os nomes antigos (CK_CONDICAO_TP_VALOR e CK_CONDICAO_TP_FONTE),
-- como no DDL da disciplina — renomeá-los aqui divergiria da fonte sem ganho.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CONDICAO_CLINICA (
    ID_CONDICAO_CLINICA   NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CD_CODIGO             VARCHAR2(60)   NOT NULL,
    DS_ROTULO             VARCHAR2(255)  NOT NULL,
    TP_DADO               VARCHAR2(20)   NOT NULL,
    TP_FONTE_VALOR        VARCHAR2(20)   DEFAULT 'RELATO' NOT NULL,
    DS_UNIDADE            VARCHAR2(20),
    FL_CRITICA            NUMBER(1)      DEFAULT 0 NOT NULL,
    AT_ATIVO              NUMBER(1)      DEFAULT 1 NOT NULL,
    ID_CLINICA            NUMBER(19)     NOT NULL,
    ID_VETERINARIO_AUTOR  NUMBER(19)     NOT NULL,
    CA_CREATED_AT         TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT         TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CONDICAO_CLINICA PRIMARY KEY (ID_CONDICAO_CLINICA),
    CONSTRAINT UK_CONDICAO_CLINICA_CODIGO UNIQUE (ID_CLINICA, CD_CODIGO),
    CONSTRAINT CK_CONDICAO_TP_VALOR CHECK (TP_DADO IN ('BOOLEANO','NUMERICO')),
    CONSTRAINT CK_CONDICAO_TP_FONTE CHECK (TP_FONTE_VALOR IN ('RELATO','ANIMAL','HISTORICO')),
    CONSTRAINT CK_CONDICAO_CRITICA CHECK (FL_CRITICA IN (0,1)),
    CONSTRAINT CK_CONDICAO_ATIVO CHECK (AT_ATIVO IN (0,1))
);

-- -----------------------------------------------------------------------------
-- T_PB_JANELA_ATENDIMENTO — um slot fixo de 30 minutos. Atendimento mais longo
-- ocupa slots consecutivos, por isso a duração não é coluna.
-- ID_CONSULTA nulo = horário livre; é essa referência que reserva o slot.
--
-- DÍVIDA CONHECIDA: cancelar consulta precisa apagar o vínculo à mão. O
-- ON DELETE SET NULL cobre exclusão, e cancelamento não é exclusão — esquecer
-- não dá erro, e o slot fica ocupado para sempre.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_JANELA_ATENDIMENTO (
    ID_JANELA_ATENDIMENTO  NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DH_DATA_HORA_INICIO    TIMESTAMP(7)  NOT NULL,
    ID_VETERINARIO         NUMBER(19)    NOT NULL,
    ID_CONSULTA            NUMBER(19),
    CA_CREATED_AT          TIMESTAMP(7)  DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT          TIMESTAMP(7),
    CONSTRAINT PK_T_PB_JANELA_ATEND PRIMARY KEY (ID_JANELA_ATENDIMENTO),
    CONSTRAINT UK_JANELA_VET_INICIO UNIQUE (ID_VETERINARIO, DH_DATA_HORA_INICIO)
);

-- -----------------------------------------------------------------------------
-- T_PB_REGISTRO_ATENDIMENTO — o que aconteceu na consulta. É o pai de
-- procedimento e prescrição: sem ele, o nível 4 não existe.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_REGISTRO_ATENDIMENTO (
    ID_REGISTRO_ATENDIMENTO  NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DT_DATA_ATENDIMENTO      TIMESTAMP(7)   NOT NULL,
    AN_ANAMNESE              VARCHAR2(2000),
    DG_DIAGNOSTICO           VARCHAR2(2000),
    TR_TRATAMENTO            VARCHAR2(2000),
    OB_OBSERVACAO            VARCHAR2(2000),
    PR_PROXIMO_RETORNO       DATE,
    PR_PROXIMA_VACINA        DATE,
    ID_ANIMAL                NUMBER(19)     NOT NULL,
    ID_CONSULTA              NUMBER(19)     NOT NULL,
    CA_CREATED_AT            TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT            TIMESTAMP(7),
    CONSTRAINT PK_T_PB_REGISTRO_ATEND PRIMARY KEY (ID_REGISTRO_ATENDIMENTO)
);

-- -----------------------------------------------------------------------------
-- T_PB_PROCEDIMENTO — vacina aplicada, exame feito.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PROCEDIMENTO (
    ID_PROCEDIMENTO          NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TP_TIPO_PROCEDIMENTO     VARCHAR2(50)   NOT NULL,
    NM_NOME                  VARCHAR2(150)  NOT NULL,
    DS_DESCRICAO             VARCHAR2(2000),
    ST_STATUS_PROCEDIMENTO   VARCHAR2(50)   NOT NULL,
    DT_DATA_PREVISTA_INICIO  TIMESTAMP(7)   NOT NULL,
    DT_DATA_PREVISTA_FIM     TIMESTAMP(7)   NOT NULL,
    AN_ANEXOS_URL            VARCHAR2(500),
    OB_OBSERVACAO            VARCHAR2(2000),
    ID_REGISTRO_ATENDIMENTO  NUMBER(19)     NOT NULL,
    ID_ANIMAL                NUMBER(19)     NOT NULL,
    ID_VETERINARIO           NUMBER(19)     NOT NULL,
    CA_CREATED_AT            TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT            TIMESTAMP(7),
    CONSTRAINT PK_T_PB_PROCEDIMENTO PRIMARY KEY (ID_PROCEDIMENTO),
    CONSTRAINT CK_PROCEDIMENTO_TIPO CHECK (TP_TIPO_PROCEDIMENTO IN
        ('VACINACAO','VERMIFUGACAO','EXAME_LABORATORIAL','EXAME_IMAGEM',
         'CIRURGIA','INTERNACAO','OUTRO')),
    CONSTRAINT CK_PROCEDIMENTO_STATUS CHECK (ST_STATUS_PROCEDIMENTO IN
        ('PENDENTE','REALIZADO','CANCELADO'))
);

-- -----------------------------------------------------------------------------
-- T_PB_PRESCRICAO — o ato assinado pela veterinária. IMUTÁVEL por decisão
-- (ADR s3-09): editar gera nova prescrição, e por isso AT_UPDATED_AT nasce nulo
-- e fica nulo por contrato — a aplicação nunca expõe UPDATE nem DELETE para
-- esta tabela.
--
-- ID_MATERIAL_ORIGEM e NR_VERSAO_ORIGEM apontam para o bulário, que só existe na
-- Sprint 4 — nascem nulos e SEM FK, porque a tabela de destino não existe.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PRESCRICAO (
    ID_PRESCRICAO            NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_MEDICAMENTO           VARCHAR2(150)  NOT NULL,
    NR_DOSE_MIN              NUMBER(8,3)    NOT NULL,
    NR_DOSE_MAX              NUMBER(8,3)    NOT NULL,
    DS_UNIDADE               VARCHAR2(20)   NOT NULL,
    NR_FREQUENCIA_DIA        NUMBER(2)      NOT NULL,
    NR_DURACAO_DIAS          NUMBER(4)      NOT NULL,
    DT_INICIO                DATE           NOT NULL,
    TX_ORIENTACAO            CLOB,
    ID_MATERIAL_ORIGEM       NUMBER(19),
    NR_VERSAO_ORIGEM         NUMBER(4),
    ID_ANIMAL                NUMBER(19)     NOT NULL,
    ID_VETERINARIO           NUMBER(19)     NOT NULL,
    ID_REGISTRO_ATENDIMENTO  NUMBER(19)     NOT NULL,
    CA_CREATED_AT            TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT            TIMESTAMP(7),
    CONSTRAINT PK_T_PB_PRESCRICAO PRIMARY KEY (ID_PRESCRICAO),
    CONSTRAINT CK_PRESCRICAO_FAIXA CHECK (NR_DOSE_MIN <= NR_DOSE_MAX),
    CONSTRAINT CK_PRESCRICAO_FREQ CHECK (NR_FREQUENCIA_DIA > 0),
    CONSTRAINT CK_PRESCRICAO_DURACAO CHECK (NR_DURACAO_DIAS > 0)
);

-- -----------------------------------------------------------------------------
-- T_PB_REGRA_PRESCRICAO — condição → ação. É o que decide a dose; nunca a IA.
-- IMUTÁVEL como a prescrição que carrega: sem UPDATE nem DELETE na aplicação.
--
-- DS_ROTULO_CONGELADO, TP_DADO_CONGELADO e TP_FONTE_VALOR_CONGELADA guardam o
-- que foi assinado (ADR s3-10), mesmo que a condição clínica mude depois.
--
-- TP_OPERADOR e NR_LIMITE são nulos quando a condição congelada é BOOLEANO —
-- não há o que comparar (CK_REGRA_COERENCIA).
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_REGRA_PRESCRICAO (
    ID_REGRA_PRESCRICAO       NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PRESCRICAO             NUMBER(19)     NOT NULL,
    ID_CONDICAO_CLINICA       NUMBER(19)     NOT NULL,
    DS_ROTULO_CONGELADO       VARCHAR2(255)  NOT NULL,
    TP_DADO_CONGELADO         VARCHAR2(20)   NOT NULL,
    TP_FONTE_VALOR_CONGELADA  VARCHAR2(20)   NOT NULL,
    TP_OPERADOR               VARCHAR2(20),
    NR_LIMITE                 NUMBER(10,3),
    TP_ACAO_DOSE              VARCHAR2(30)   NOT NULL,
    NR_ORDEM                  NUMBER(3)      NOT NULL,
    CA_CREATED_AT             TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT             TIMESTAMP(7),
    CONSTRAINT PK_T_PB_REGRA_PRESCRICAO PRIMARY KEY (ID_REGRA_PRESCRICAO),
    CONSTRAINT CK_REGRA_TP_VALOR CHECK (TP_DADO_CONGELADO IN ('BOOLEANO','NUMERICO')),
    CONSTRAINT CK_REGRA_TP_FONTE CHECK (TP_FONTE_VALOR_CONGELADA IN ('RELATO','ANIMAL','HISTORICO')),
    CONSTRAINT CK_REGRA_OPERADOR CHECK (TP_OPERADOR IN
        ('MAIOR_QUE','MAIOR_OU_IGUAL','MENOR_QUE','MENOR_OU_IGUAL','IGUAL')),
    CONSTRAINT CK_REGRA_ACAO CHECK (TP_ACAO_DOSE IN
        ('DOSE_MIN','DOSE_MAX','DOSE_PADRAO','ACIONAR_CLINICA','SUSPENDER')),
    CONSTRAINT CK_REGRA_COERENCIA CHECK (
        (TP_DADO_CONGELADO = 'NUMERICO' AND TP_OPERADOR IS NOT NULL AND NR_LIMITE IS NOT NULL)
     OR (TP_DADO_CONGELADO = 'BOOLEANO' AND TP_OPERADOR IS NULL AND NR_LIMITE IS NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_CHECKIN — o cabeçalho: um relato por pet e por momento
-- (decisão D). Cobre todos os remédios de uma vez: "as fezes tavam moles" vale
-- para toda prescrição avaliada naquele check-in.
--
-- Guarda a TRANSCRIÇÃO, não o áudio (ADR s3-18) — não há AU_AUDIO_URL.
-- DS_TIC_UTILIZADA atende o Art. 13 §5º da resolução do CFMV.
-- Sem coluna de status: a linha só nasce quando o tutor confirma.
--
-- DOIS MODOS DE RELATO (ADR s3-24, §6). ID_ITEM_PLANO_CUIDADO nulo é o relato
-- GERAL do dia — "como o Thor passou?" — e é o caminho principal. Preenchido, é
-- relato sobre um item específico.
--
-- A unicidade (ID_ANIMAL, DT_REFERENCIA, ID_ITEM_PLANO_CUIDADO) dá exatamente
-- isso sem trigger e sem regra na aplicação: **o Oracle conta chave
-- parcialmente nula para unicidade**, então o nulo permite um único relato geral
-- por pet por dia, e cada item aceita o seu. É a mesma propriedade que, mal
-- usada, quebraria o índice do item (ver UX_ITEM_PRESC_DATA adiante) — aqui ela
-- trabalha a favor.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CHECKIN (
    ID_CHECKIN              NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL               NUMBER(19)     NOT NULL,
    ID_ITEM_PLANO_CUIDADO   NUMBER(19),
    DT_REFERENCIA           DATE           NOT NULL,
    DH_REGISTRADO_EM        TIMESTAMP(7)   NOT NULL,
    TX_NARRATIVA            CLOB           NOT NULL,
    TX_OBSERVACOES_GERAIS   CLOB,
    DS_TIC_UTILIZADA        VARCHAR2(120),
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CHECKIN PRIMARY KEY (ID_CHECKIN),
    CONSTRAINT UK_CHECKIN_ANIMAL_DIA UNIQUE (ID_ANIMAL, DT_REFERENCIA, ID_ITEM_PLANO_CUIDADO)
);

-- -----------------------------------------------------------------------------
-- T_PB_CONDICAO_OBSERVADA — o que a IA extraiu do relato: uma linha por condição
-- observada. Aponta para o CATÁLOGO, não para a regra — o tutor pode relatar
-- condição que nenhuma regra cobre ("apetite reduzido"), e isso fica registrado.
-- Imutável: AT_UPDATED_AT fica nulo por contrato.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CONDICAO_OBSERVADA (
    ID_CONDICAO_OBSERVADA     NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_CHECKIN   NUMBER(19)     NOT NULL,
    ID_CONDICAO_CLINICA     NUMBER(19)     NOT NULL,
    CD_CODIGO_CONGELADO     VARCHAR2(60)   NOT NULL,
    BL_VALOR_BOOLEANO       NUMBER(1),
    NR_VALOR_NUMERICO       NUMBER(10,3),
    NR_CONFIANCA            NUMBER(5,4)    NOT NULL,
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CONDICAO_OBSERVADA PRIMARY KEY (ID_CONDICAO_OBSERVADA),
    CONSTRAINT CK_COBS_BOOLEANO CHECK (BL_VALOR_BOOLEANO IN (0,1)),
    -- [proposta desta sessão] confiança da IA é probabilidade, não escala livre.
    CONSTRAINT CK_COBS_CONFIANCA CHECK (NR_CONFIANCA BETWEEN 0 AND 1),
    -- [proposta desta sessão] exatamente um dos dois valores é preenchido,
    -- conforme o TP_DADO da condição.
    CONSTRAINT CK_COBS_UM_VALOR CHECK (
        (BL_VALOR_BOOLEANO IS NOT NULL AND NR_VALOR_NUMERICO IS NULL)
     OR (BL_VALOR_BOOLEANO IS NULL AND NR_VALOR_NUMERICO IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_USUARIO — login único para os dois perfis. O Java emite o JWT; o .NET
-- valida o mesmo token (ADRs s3-02 e s3-06).
--
-- Exatamente um dos dois ids de vínculo é preenchido, conforme o perfil.
-- Sem AT_UPDATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_USUARIO (
    ID_USUARIO       NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DS_LOGIN         VARCHAR2(120)  NOT NULL,
    DS_SENHA_HASH    VARCHAR2(100)  NOT NULL,
    TP_PERFIL        VARCHAR2(20)   NOT NULL,
    ID_VETERINARIO   NUMBER(19),
    ID_RESPONSAVEL   NUMBER(19),
    AT_ATIVO         NUMBER(1)      DEFAULT 1 NOT NULL,
    CA_CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_PB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_LOGIN UNIQUE (DS_LOGIN),
    CONSTRAINT CK_USUARIO_PERFIL CHECK (TP_PERFIL IN ('VET','TUTOR')),
    CONSTRAINT CK_USUARIO_ATIVO CHECK (AT_ATIVO IN (0,1)),
    -- [proposta desta sessão] o vínculo tem que casar com o perfil.
    CONSTRAINT CK_USUARIO_VINCULO CHECK (
        (TP_PERFIL = 'VET'   AND ID_VETERINARIO IS NOT NULL AND ID_RESPONSAVEL IS NULL)
     OR (TP_PERFIL = 'TUTOR' AND ID_RESPONSAVEL IS NOT NULL AND ID_VETERINARIO IS NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_PLANO_CUIDADO — o plano vivo do pet.
-- ID_ANIMAL e ID_CONSULTA atravessam para o .NET (decisão B).
-- ID_PROTOCOLO é nulável: plano de TRATAMENTO nasce de prescrição, sem molde.
-- Sem cancelamento: não é ação da Sprint 3 (decisão I).
--
-- TP_CATEGORIA_PLANO é própria do plano (ADR s3-24, §4), e não herdada do protocolo.
-- Antes, saber a categoria exigia join com T_PB_PROTOCOLO — e isso EXCLUÍA todo
-- plano com ID_PROTOCOLO nulo, que é justamente o de tratamento. A query de
-- idempotência do motor tinha esse furo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PLANO_CUIDADO (
    ID_PLANO_CUIDADO          NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL                 NUMBER(19)    NOT NULL,
    ID_CONSULTA               NUMBER(19),
    ID_PROTOCOLO              NUMBER(19),
    TP_CATEGORIA_PLANO              VARCHAR2(20)  NOT NULL,
    ST_STATUS_PLANO                 VARCHAR2(50)  NOT NULL,
    CA_CREATED_AT             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_PLANO PRIMARY KEY (ID_PLANO_CUIDADO),
    CONSTRAINT CK_PLANO_STATUS CHECK (ST_STATUS_PLANO IN ('ATIVO','CONCLUIDO','CANCELADO')),
    CONSTRAINT CK_PLANO_CATEGORIA CHECK (TP_CATEGORIA_PLANO IN
        ('PREVENTIVO','POS_CIRURGICO','TRATAMENTO'))
);

-- -----------------------------------------------------------------------------
-- T_PB_ITEM_PLANO_CUIDADO — o item do checklist: uma linha por dose ou aplicação.
-- Um tratamento de 10 dias são 10 linhas com o mesmo ID_PRESCRICAO.
--
-- TP_ORIGEM é o que decide o rótulo da tela: PRESCRICAO é "você faz em casa",
-- PROTOCOLO é "na clínica". Não existe coluna de executor — é derivado.
--
-- ID_REGRA_PROTOCOLO é nulável: item vindo de prescrição não tem molde.
-- ID_PRESCRICAO e ID_PROCEDIMENTO atravessam para o .NET (decisão B).
-- Sem CA_CREATED_AT: a entidade não tem o campo.
--
-- A EXECUÇÃO MORA AQUI (ADR s3-24, §5). T_PB_CHECKIN_RESULTADO deixou de
-- existir. O item já carregava metade do padrão de baixa — ID_PROCEDIMENTO e
-- DT_EXECUTADO_EM, o "quem me baixou" do item da clínica. Recebe agora a outra
-- metade, para o item de casa: ID_CHECKIN, TP_DESFECHO, NR_DOSE_APLICADA e
-- ID_REGRA_APLICADA.
--
-- Some com isso uma duplicidade que ninguém queria: ST_STATUS_ITEM dizia *se* o item
-- foi feito, e TP_DESFECHO dizia *se e por quê*. Duas verdades, um fato.
--
-- O PREÇO, aceito na decisão: quatro colunas nulas em todo item de origem
-- PROTOCOLO. O item já tinha duas assim, então a forma não é nova.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_ITEM_PLANO_CUIDADO (
    ID_ITEM_PLANO_CUIDADO           NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PLANO_CUIDADO   NUMBER(19)     NOT NULL,
    ID_REGRA_PROTOCOLO       NUMBER(19),
    TP_ORIGEM                 VARCHAR2(20)   NOT NULL,
    ID_PRESCRICAO             NUMBER(19),
    TP_TIPO_CUIDADO                   VARCHAR2(50)   NOT NULL,
    NM_NOME                   VARCHAR2(255)  NOT NULL,
    DT_DATA_ALVO              DATE           NOT NULL,
    ST_STATUS_ITEM                 VARCHAR2(50)   NOT NULL,
    OB_OBSERVACAO             VARCHAR2(2000),
    ID_PROCEDIMENTO           NUMBER(19),
    DT_EXECUTADO_EM           TIMESTAMP,
    ID_CHECKIN                NUMBER(19),
    TP_DESFECHO               VARCHAR2(30),
    NR_DOSE_APLICADA          NUMBER(8,3),
    ID_REGRA_APLICADA         NUMBER(19),
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_ITEM_PLANO_CUIDADO PRIMARY KEY (ID_ITEM_PLANO_CUIDADO),
    CONSTRAINT CK_ITEM_ORIGEM CHECK (TP_ORIGEM IN ('PROTOCOLO','PRESCRICAO')),
    CONSTRAINT CK_ITEM_TIPO CHECK (TP_TIPO_CUIDADO IN
        ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')),
    CONSTRAINT CK_ITEM_STATUS CHECK (ST_STATUS_ITEM IN
        ('PENDENTE','REALIZADO','CANCELADO','ATRASADO')),
    -- [proposta desta sessão] item de prescrição precisa dizer de qual;
    -- item de protocolo precisa do molde que o gerou.
    CONSTRAINT CK_ITEM_ORIGEM_COER CHECK (
        (TP_ORIGEM = 'PRESCRICAO' AND ID_PRESCRICAO IS NOT NULL)
     OR (TP_ORIGEM = 'PROTOCOLO'  AND ID_REGRA_PROTOCOLO IS NOT NULL)),
    CONSTRAINT CK_ITEM_DESFECHO CHECK (TP_DESFECHO IN
        ('DOSE_CALCULADA','ACIONAR_CLINICA','SEM_DOSE')),
    -- [proposta desta sessão, adotada no ADR s3-24] o CHECK da dose virou
    -- TERNÁRIO com a fusão. Antes era binário, porque toda linha da tabela morta
    -- tinha desfecho. Agora item de origem PROTOCOLO não tem nenhum — e sem o
    -- primeiro ramo, todo item de vacina seria recusado.
    CONSTRAINT CK_ITEM_DESFECHO_DOSE CHECK (
        (TP_DESFECHO IS NULL             AND NR_DOSE_APLICADA IS NULL)
     OR (TP_DESFECHO =  'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NOT NULL)
     OR (TP_DESFECHO <> 'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NULL))
);


-- =============================================================================
--


-- =============================================================================
-- FOREIGN KEYS INTERNAS AO CUIDADO
-- =============================================================================
-- Voltaram do V2 com o fim dele (ADR s3-25): as duas pontas vivem neste schema.
ALTER TABLE T_PB_USUARIO ADD CONSTRAINT FK_USUARIO_RESPONSAVEL
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES T_PB_RESPONSAVEL (ID_RESPONSAVEL);
ALTER TABLE T_PB_USUARIO ADD CONSTRAINT FK_USUARIO_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);

ALTER TABLE T_PB_VETERINARIO ADD CONSTRAINT FK_VETERINARIO_CLINICA
    FOREIGN KEY (ID_CLINICA) REFERENCES T_PB_CLINICA (ID_CLINICA);

ALTER TABLE T_PB_ANIMAL ADD CONSTRAINT FK_ANIMAL_RESPONSAVEL
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES T_PB_RESPONSAVEL (ID_RESPONSAVEL);

ALTER TABLE T_PB_PLANO_CUIDADO ADD CONSTRAINT FK_PLANO_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_PLANO_CUIDADO ADD CONSTRAINT FK_PLANO_CONSULTA
    FOREIGN KEY (ID_CONSULTA) REFERENCES T_PB_CONSULTA (ID_CONSULTA);

ALTER TABLE T_PB_CHECKIN ADD CONSTRAINT FK_CHECKIN_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);

ALTER TABLE T_PB_CONSULTA ADD CONSTRAINT FK_CONSULTA_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_CONSULTA ADD CONSTRAINT FK_CONSULTA_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);

ALTER TABLE T_PB_CONDICAO_CLINICA ADD CONSTRAINT FK_CONDICAO_CLINICA
    FOREIGN KEY (ID_CLINICA) REFERENCES T_PB_CLINICA (ID_CLINICA);
ALTER TABLE T_PB_CONDICAO_CLINICA ADD CONSTRAINT FK_CONDICAO_AUTOR
    FOREIGN KEY (ID_VETERINARIO_AUTOR) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);

-- O SET NULL libera o slot quando a consulta é EXCLUÍDA. Cancelamento não é
-- exclusão: aquele caminho precisa apagar o vínculo no código.
ALTER TABLE T_PB_JANELA_ATENDIMENTO ADD CONSTRAINT FK_JANELA_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);
ALTER TABLE T_PB_JANELA_ATENDIMENTO ADD CONSTRAINT FK_JANELA_CONSULTA
    FOREIGN KEY (ID_CONSULTA) REFERENCES T_PB_CONSULTA (ID_CONSULTA) ON DELETE SET NULL;

ALTER TABLE T_PB_REGISTRO_ATENDIMENTO ADD CONSTRAINT FK_REGATEND_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_REGISTRO_ATENDIMENTO ADD CONSTRAINT FK_REGATEND_CONSULTA
    FOREIGN KEY (ID_CONSULTA) REFERENCES T_PB_CONSULTA (ID_CONSULTA);

ALTER TABLE T_PB_PROCEDIMENTO ADD CONSTRAINT FK_PROCED_REGATEND
    FOREIGN KEY (ID_REGISTRO_ATENDIMENTO) REFERENCES T_PB_REGISTRO_ATENDIMENTO (ID_REGISTRO_ATENDIMENTO);
ALTER TABLE T_PB_PROCEDIMENTO ADD CONSTRAINT FK_PROCED_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_PROCEDIMENTO ADD CONSTRAINT FK_PROCED_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);

ALTER TABLE T_PB_PRESCRICAO ADD CONSTRAINT FK_PRESCRICAO_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_PRESCRICAO ADD CONSTRAINT FK_PRESCRICAO_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);
ALTER TABLE T_PB_PRESCRICAO ADD CONSTRAINT FK_PRESCRICAO_REGATEND
    FOREIGN KEY (ID_REGISTRO_ATENDIMENTO) REFERENCES T_PB_REGISTRO_ATENDIMENTO (ID_REGISTRO_ATENDIMENTO);

-- Restrict em tudo que aponta para catálogo ou ato assinado.
ALTER TABLE T_PB_REGRA_PRESCRICAO ADD CONSTRAINT FK_REGRA_PRESCRICAO
    FOREIGN KEY (ID_PRESCRICAO) REFERENCES T_PB_PRESCRICAO (ID_PRESCRICAO);
ALTER TABLE T_PB_REGRA_PRESCRICAO ADD CONSTRAINT FK_REGRA_CONDICAO
    FOREIGN KEY (ID_CONDICAO_CLINICA) REFERENCES T_PB_CONDICAO_CLINICA (ID_CONDICAO_CLINICA);

ALTER TABLE T_PB_CONDICAO_OBSERVADA ADD CONSTRAINT FK_COBS_CONDICAO
    FOREIGN KEY (ID_CONDICAO_CLINICA) REFERENCES T_PB_CONDICAO_CLINICA (ID_CONDICAO_CLINICA);

ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_PLANO
    FOREIGN KEY (ID_PLANO_CUIDADO) REFERENCES T_PB_PLANO_CUIDADO (ID_PLANO_CUIDADO) ON DELETE CASCADE;
-- CICLO DELIBERADO, e por isso as duas colunas são nuláveis: o check-in aponta
-- para o item de que fala (relato por item), e o item aponta para o check-in que
-- o baixou. São relações diferentes entre as mesmas tabelas. O Oracle aceita,
-- porque nenhuma ponta é obrigatória — mas a CARGA precisa de ORDEM: primeiro
-- os relatos gerais, depois os itens, e só então o relato por item. Ver o
-- bloco 03.
ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_CHECKIN
    FOREIGN KEY (ID_CHECKIN) REFERENCES T_PB_CHECKIN (ID_CHECKIN);
ALTER TABLE T_PB_CHECKIN ADD CONSTRAINT FK_CHECKIN_ITEM
    FOREIGN KEY (ID_ITEM_PLANO_CUIDADO) REFERENCES T_PB_ITEM_PLANO_CUIDADO (ID_ITEM_PLANO_CUIDADO);

--


-- =============================================================================
-- ÍNDICES
-- Oracle já indexa PK e UNIQUE. Aqui ficam só os de FK e de consulta.
-- =============================================================================

-- "que horários deste vet estão livres?" varre por ID_CONSULTA IS NULL
CREATE INDEX IX_JANELA_CONSULTA ON T_PB_JANELA_ATENDIMENTO (ID_CONSULTA);

-- o motor lê as regras de uma prescrição na ordem assinada
CREATE INDEX IX_REGRA_PRESC_ORDEM ON T_PB_REGRA_PRESCRICAO (ID_PRESCRICAO, NR_ORDEM);

CREATE INDEX IX_CHECKIN_ANIMAL_DATA ON T_PB_CHECKIN (ID_ANIMAL, DH_REGISTRADO_EM);
CREATE INDEX IX_ITEM_PLANO_DATA ON T_PB_ITEM_PLANO_CUIDADO (ID_PLANO_CUIDADO, DT_DATA_ALVO);
CREATE INDEX IX_ITEM_PRESCRICAO ON T_PB_ITEM_PLANO_CUIDADO (ID_PRESCRICAO);
CREATE INDEX IX_ITEM_DESFECHO ON T_PB_ITEM_PLANO_CUIDADO (TP_DESFECHO);

-- A TRAVA DA ADESÃO, herdada de UK_RESULTADO_PRESC_DATA quando a execução virou
-- coluna do item. Índice FUNCIONAL, e não UNIQUE composta, de propósito: no
-- Oracle uma chave PARCIALMENTE nula conta para a unicidade, e todo item de
-- origem PROTOCOLO tem ID_PRESCRICAO nulo — duas vacinas na mesma data
-- colidiriam. Com o CASE, chave inteiramente nula repete à vontade.
CREATE UNIQUE INDEX UX_ITEM_PRESC_DATA ON T_PB_ITEM_PLANO_CUIDADO
    (ID_PRESCRICAO, CASE WHEN ID_PRESCRICAO IS NOT NULL THEN DT_DATA_ALVO END);
