-- =============================================================================
-- V2 — SEED DE DEMONSTRAÇÃO
-- =============================================================================
-- Uma clínica, um veterinário, um responsável e os dois usuários que a banca
-- usa para entrar. Com banco por serviço (ADR s3-25) este schema nasce vazio, e
-- quem semeia o vínculo do usuário é este arquivo — não há mais migration do
-- .NET criando clínica, veterinário e responsável neste banco.
--
-- POR QUE OS IDS SÃO EXPLÍCITOS
--   FK_USUARIO_VETERINARIO e FK_USUARIO_RESPONSAVEL exigem ids conhecidos no
--   momento do INSERT do usuário. As colunas são GENERATED BY DEFAULT ON NULL,
--   então aceitam valor explícito.
--
-- POR QUE O ALTER NO FIM
--   Inserir id explícito NÃO avança o gerador do identity. Sem os ALTER abaixo
--   a primeira clínica criada pela aplicação recebe id 1 e colide com o seed.
--   START WITH LIMIT VALUE reposiciona o gerador em MAX(id)+1.
--
-- AS SENHAS
--   As duas são a mesma senha de demonstração, cifrada em BCrypt (cost 10, 60
--   caracteres — cabe no VARCHAR2(100) de DS_SENHA_HASH). O valor em claro está
--   no corpo do PR: é dado de demonstração, e a banca precisa dele para entrar.
-- =============================================================================

-- --- a clínica --------------------------------------------------------------
INSERT INTO T_PB_CLINICA (ID_CLINICA, NM_NOME_CLINICA, NR_CNPJ, TL_TELEFONE, EM_EMAIL)
VALUES (1, 'Clinica PetBuddies Vila Mariana', '12345678000199', '1140028922',
        'contato@petbuddies.com');

-- --- o veterinário ----------------------------------------------------------
INSERT INTO T_PB_VETERINARIO (ID_VETERINARIO, NM_NOME_VETERINARIO, NR_CRMV, EM_EMAIL,
                              AT_ATIVO, ID_CLINICA)
VALUES (1, 'Ana Souza', 'SP-12345', 'ana@clinica.com', 1, 1);

-- --- o responsável ----------------------------------------------------------
INSERT INTO T_PB_RESPONSAVEL (ID_RESPONSAVEL, NM_NOME_RESPONSAVEL, TL_TELEFONE, EM_EMAIL)
VALUES (1, 'Maria Oliveira', '11987654321', 'maria@email.com');

-- --- o vet ------------------------------------------------------------------
INSERT INTO T_PB_USUARIO (DS_LOGIN, DS_SENHA_HASH, TP_PERFIL, ID_VETERINARIO, AT_ATIVO)
VALUES ('ana@clinica.com',
        '$2a$10$v20f4a3MJrUHeusflIz/Y.JaUxfxFpAa18BztNQEuaNW8nXOaQnou',
        'VET', 1, 1);

-- --- o tutor ----------------------------------------------------------------
INSERT INTO T_PB_USUARIO (DS_LOGIN, DS_SENHA_HASH, TP_PERFIL, ID_RESPONSAVEL, AT_ATIVO)
VALUES ('maria@email.com',
        '$2a$10$m0xXaZ6pPj7kFwdkruEx4u.wuEPnPL05ZUVD9Sx2KEtLgdTi8fwUK',
        'TUTOR', 1, 1);

-- --- reposiciona os geradores depois dos ids explícitos ---------------------
ALTER TABLE T_PB_CLINICA     MODIFY (ID_CLINICA     GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE T_PB_VETERINARIO MODIFY (ID_VETERINARIO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE T_PB_RESPONSAVEL MODIFY (ID_RESPONSAVEL GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
